- name: Cargar variables específicas del sistema
  include_vars: "{{ ansible_os_family | lower }}.yml"

- name: Instalar Apache
  ansible.builtin.import_tasks: "apache.yml"

- name: Instalar PHP
  ansible.builtin.import_tasks: php.yml

- name: Descargar e instalar WordPress
  ansible.builtin.import_tasks: wordpress.yml 
