- name: Instalar PHP
  ansible.builtin.package:
    name: "{{ php_packages }}"
    state: present
    update_cache: yes
  become: yes
 
- name: Verificar versión de PHP
  ansible.builtin.command: php -v
  register: php_version
  changed_when: false
  ignore_errors: yes

- name: Mostrar versión instalada de PHP
  ansible.builtin.debug:
    msg: "PHP instalado: {{ php_version.stdout }}"
