---
- name: Instalar dependencias para WordPress
  ansible.builtin.package:
    name:
      - unzip
      - curl
    state: present
    update_cache: yes

- name: Descargar WordPress
  get_url:
    url: https://wordpress.org/wordpress-6.7.2.zip
    dest: /tmp/wordpress.zip

- name: Descomprimir Wordpress
  unarchive:
    src: /tmp/wordpress.zip
    dest: /srv/
    remote_src: yes
 

- name: Crea grupo "wordpress"
  group: name=wordpress

- name: Crea usuario "wordpress"
  user: name=wordpress group=wordpress home=/srv/wordpress/



- name: Copiar archivo de configuración wp-config.php
  ansible.builtin.template:
    src: wp-config.php.j2
    dest: /srv/wordpress/wp-config.php
    owner: "{{ web_user }}"
    group: "{{ web_group }}"
    mode: '0644'

- name: Ajustar contexto SELinux para WordPress (solo en RHEL/CentOS/Rocky)
  command: chcon -Rt httpd_sys_content_t /srv/wordpress
  when:
    - ansible_os_family == "RedHat"
    - ansible_selinux.status == "enabled"
  become: true
