define: &wp_version: "6.7.2"
define: &mysql_root_password: "rootpass"
define: &wordpress_db_name: "wordpress_db"
define: &wordpress_db_user: "wordpress_user"
define: &wordpress_db_password: "wordpress_pass"

mysql_databases:
  - name: *wordpress_db_name
    encoding: utf8
    collation: utf8_general_ci

mysql_users:
  - name: *wordpress_db_user
    host: "%"
    password: *wordpress_db_password
    priv: "wordpress_db.*:ALL"
