---
dependency:
  name: galaxy
driver:
  name: docker

platforms:
  - name: instance-debian
    image: geerlingguy/docker-debian12-ansible
  - name: instance-ubuntu
    image: geerlingguy/docker-ubuntu2404-ansible
  - name: instance-rocky
    image: geerlingguy/docker-rockylinux9-ansible
  - name: instance-centos
    image: geerlingguy/docker-centos8-ansible


provisioner:
  name: ansible

verifier:
  name: ansible
