---
- name: Verify role effects
  hosts: all
  become: true
  tasks:
    - name: Check if apache2 is running
      ansible.builtin.service:
        name: apache2
        state: started
      register: apache_status

    - name: Assert apache2 is running
      ansible.builtin.assert:
        that:
          - apache_status.state == "started"

    - name: Check if port 80 is open
      ansible.builtin.wait_for:
        port: 80
        timeout: 5

    - name: Check if wp-config.php exists
      ansible.builtin.stat:
        path: /srv/wordpress/wp-config.php
      register: wp_config

    - name: Assert wp-config.php exists
      ansible.builtin.assert:
        that:
          - wp_config.stat.exists
